name: CLI

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/cli.yml
      - packages/@expo/cli/**
      - packages/@expo/metro-runtime/**
      - packages/@expo/metro-config/src/**
      - packages/@expo/config/src/**
      - packages/@expo/config-plugins/src/**
      - packages/@expo/env/src/**
      - packages/@expo/json-file/src/**
      - packages/@expo/package-manager/src/**
      - packages/@expo/prebuild-config/src/**
      - packages/@expo/server/src/**
      - packages/create-expo/**
      - packages/expo-router/**
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/cli.yml
      - packages/@expo/cli/**
      - packages/@expo/metro-runtime/**
      - packages/@expo/metro-config/src/**
      - packages/@expo/config/src/**
      - packages/@expo/config-plugins/src/**
      - packages/@expo/env/src/**
      - packages/@expo/json-file/src/**
      - packages/@expo/package-manager/src/**
      - packages/@expo/prebuild-config/src/**
      - packages/@expo/server/src/**
      - packages/create-expo/**
      - packages/expo-router/**
      - yarn.lock
  schedule:
    - cron: 0 14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        shard: [1, 2, 3]
        include:
          - os: ubuntu-22.04
            shell: bash
            yarn-cache: ~/.cache/yarn
          - os: windows-2022
            shell: cmd
            yarn-cache: C:\Users\runneradmin\AppData\Local\Yarn\Cache
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      
      - name: Setup Git
        if: matrix.os == 'windows-2022'
        run: git config --global core.autocrlf false
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: ⬇️ Fetch commits from base branch
        shell: bash
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

      - name: ♻️ Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ${{ matrix.yarn-cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🧶 Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile --ignore-scripts
      
      - name: Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🔎 Type Check CLI (Unix)
        if: matrix.os == 'ubuntu-22.04'
        run: yarn typecheck
        working-directory: packages/@expo/cli
        
      - name: 🔎 Type Check CLI (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          yarn tsc --noEmit
        working-directory: packages/@expo/cli
        
      - name: E2E Test CLI (Unix)
        if: matrix.os == 'ubuntu-22.04'
        run: yarn test:e2e --shard ${{ matrix.shard }}/${{ strategy.job-total }}
        working-directory: packages/@expo/cli
        
      # - name: E2E Test CLI (Windows)
      #   if: matrix.os == 'windows-2022'
      #   run: yarn test:e2e --shard=${{ matrix.shard }}/${{ strategy.job-total }}
      #   working-directory: packages/@expo/cli

  web:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ⬇️ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: ♻️ Restore Yarn Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🧶 Install node modules in root dir
        run: yarn install --prefer-offline --frozen-lockfile --ignore-scripts
      
      - name: Build Expo CLI
        run: yarn workspace @expo/cli prepare
        
      - name: 🎭 Get installed Playwright version for cache key
        run: echo "PLAYWRIGHT_VERSION=$(npm info @playwright/test version)" >> $GITHUB_ENV
      - name: 🎭 Cache Playwright browser binaries
        uses: actions/cache@v4
        id: playwright-browser-cache
        with:
          path: |
            ~/.cache/ms-playwright
            ~/AppData/Local/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: 🎭 Install Playwright Browsers
        run: bun playwright install --with-deps chromium
        working-directory: packages/@expo/cli
        if: steps.playwright-browser-cache.outputs.cache-hit != 'true'

      - name: E2E (playwright) Test CLI
        run: yarn test:playwright
        working-directory: packages/@expo/cli
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/@expo/cli/playwright-report/
          retention-days: 30