name: Router Maestro E2E

on:
  workflow_run:
    workflows: ['Test Suite']
    types:
      - success

jobs:
  should-run-check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - id: check
        run: |
          git fetch origin ${{ github.event.workflow_run.head_branch }}
          DIFF=$(git diff --name-only origin/main...origin/${{ github.event.workflow_run.head_branch }} | grep -E '^(packages/expo-router|apps/router-e2e)/' || true)
          if [ -z "$DIFF" ]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
  ios-dev-maestro-router:
    runs-on: macos-latest
    needs: should-run-check
    if: needs.should-run-check.outputs.should_run == 'true'
    env:
      E2E_ROUTER_SRC: maestro-development-build
      E2E_ROUTER_JS_ENGINE: hermes
      E2E_CANARY_ENABLED: 1
      E2E_ROUTER_EXPO_PORT: 8081
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🌠 Download builds
        uses: actions/download-artifact@v4
        with:
          name: bare-expo-ios-builds
          path: apps/router-e2e/ios/build/RouterApp.app
      - name: 🍺 Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
      - name: 🧶 Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build Expo CLI
        run: yarn workspace @expo/cli prepare

      - name: Start Expo CLI
        working-directory: apps/router-e2e
        run: |
          # Run the Expo Dev Server in the background
          node ../../packages/@expo/cli/build/bin/cli run:ios --binary apps/router-e2e/ios/build/RouterApp.app --port $E2E_ROUTER_EXPO_PORT &
          sleep 10

      - name: Preload Expo bundle
        run: |
          # Get the bundle URL
          echo $E2E_ROUTER_EXPO_SERVER
          BUNDLE_INFO=$(curl --silent --show-error --fail -H "Content-Type: multipart/mixed" -H "expo-platform: ios" "http://localhost:${E2E_ROUTER_EXPO_PORT}")
          BUNDLE_URL=$(echo $BUNDLE_INFO | jq -r ".launchAsset.url")

          # Start the build early by starting the build in the background
          curl --silent --output /dev/null --show-error --fail $BUNDLE_URL &

      - name: Run Maestro iOS tests
        working-directory: apps/router-e2e
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
        run: |
          # Run the Expo Dev Server in the background
          maestro test __e2e__/maestro-development-build/__tests__/ --no-ansi --format=junit --debug-output .logs

      - name: Log output
        if: ${{ failure() }}
        working-directory: apps/router-e2e/.logs/.maestro/tests
        run: |
          cd $(find . -type d -name "202*"  | head -n 1)
          cat maestro.log
          exit 1
